### ISSUE TITLE
Enable open CORS on development y-sweet server

### ISSUE THREAD

**Issue by colelawrence** [drifting-in-space/y-sweet#130]
<img width="603" alt="2023-09-15" src="https://github.com/drifting-in-space/y-sweet/assets/2925395/9fb61dca-21d4-4451-ad6e-e40b3f753112">

I'm just running y-sweet locally, and I was assuming that I might be able to either configure CORS via cli or it would be open. I think that this is something for y-sweet to implement if I remember correctly.

I don't pass in a connection string from my Next.js frontend, I just use
```tsx
export function Outer() {
  const process = useProcess();
  const [clientToken, setClientToken] = useState<ClientToken | undefined>();
  useEffect(() => {
    getOrCreateDoc(process.processID, {}).then(setClientToken);
  }, [process.processID]);
  return (
    <>
      {clientToken ? (
        <YDocProvider clientToken={clientToken}>
          <Inner />
        </YDocProvider>
      ) : (
        <Spinner text="Connecting..." />
      )}
    </>
  );
}
```

**Comment by paulgb** [comment]
Our recommendation is that `getOrCreateDoc` only be used from the server side, since in production it needs the server token which is intended to be a server-only secret. Is this a 100% client-side React app, or is there a server piece where you could put `getOrCreateDoc`? (If there is a non-JS server, you can also hit the REST API that underlies `getOrCreateDoc` directly)

**Comment by colelawrence** [comment]
Okay! I understand. My app is exported to static files. This makes a lot of sense, though. I will move it to a server function. I am working on a prototype, so I didn't think it would be a big issue.

**Comment by SebastianStehle** [comment]
I have a pure client side code, it is similar to jsfiddle and so on where you don't have to login. Is this really a no go?

**Comment by rolyatmax** [comment]
@SebastianStehle If the auth token for your y-sweet server is in the client, then anyone can use that token to create / edit / delete any of the docs on your y-sweet instance.
