### ISSUE TITLE
Client generated doc ID

### ISSUE THREAD

**Issue by SebastianStehle** [drifting-in-space/y-sweet#141]
Hi,

is it possible to create the doc ID from the client? I figure it out how to create a document from my go code. Ideally I would call it in the client directly.

Just a simple API call that creates the doc if not created yet, would be ideal.

At the moment I also get an invalid JSON response:
![image](https://github.com/drifting-in-space/y-sweet/assets/1236435/9360a3f7-bf8d-4f9b-a324-e7437f6dd13b)

**Comment by paulgb** [comment]
Good catch. Yes, we have this now! Will close this, but let me know if anything isn't clear.
