### ISSUE TITLE
Using YDocProvider in layout of Next.js 13.x with App routing 

### ISSUE THREAD

**Issue by seleckis** [drifting-in-space/y-sweet#150]
In Next.js 13 with App Routing y-sweet works well only when used in a page, but I need to define provider on the highest level of my web app in `layout.tsx` file.

By the [Next.js documentation](https://nextjs.org/docs/app/api-reference/functions/use-search-params#layouts) it is not possible to get `searchParams` from props, but only by converting `layout.tsx` to client component with `"use client";` and then using `useSearchParams` hook I can get searchParams. In this case `await getOrCreateDoc` is not possible to use because [client components should not be asynchronous](https://nextjs.org/docs/messages/no-async-client-component).

Any suggestion or improvement?

**Comment by rolyatmax** [comment]
Would it be possible to take whatever state you're relying on in the `searchParams` and make it part of the route? Route params are available in layouts and can be passed to Server Components.

Say, if you had a route like `/doc/[docID]`, you could do something like this:

```tsx
// app/doc/[docID]/layout.tsx

export default async function DocLayout({ params, children }: { params: { docID: string }, children: ReactNode }) {
  const clientToken = await getOrCreateDoc(docID, YOUR_SECRET_CONNECTION_STRING)
  return <YDocProvider clientToken={clientToken}>{children}</YDocProvider>
}
```

I _think_ you could also use optional catch-all segments like this maybe?:

```tsx
// app/[[...segments]]/layout.tsx

export default async function DocLayout({ params }: { params: { segments: string[] }, children: ReactNode }) {
  const docID = getDocIdFromSegments(segments)
  const clientToken = await getOrCreateDoc(docID, YOUR_SECRET_CONNECTION_STRING)
  return <YDocProvider clientToken={clientToken}>{children}</YDocProvider>
}
```

**Comment by seleckis** [comment]
Thanks. This seems handy to me.
