### ISSUE TITLE
Improvement: Use custom provider

### ISSUE THREAD

**Issue by seleckis** [drifting-in-space/y-sweet#151]
Would be awesome to have an ability to pass custom provider to `YDocProvider` as prop. For example I use Hocuspocus server and I can create client provider by:
```ts
import { HocuspocusProvider } from "@hocuspocus/provider";

export const doc = new Y.Doc();

const provider = new HocuspocusProvider({
  url: "ws://127.0.0.1:1234",
  name: "app",
  document: doc,
  connect: false,
  token: "token",
});
```
And then I would like to pass it to `YDocProvider` through props.

What do you think?

**Comment by websiddu** [comment]
You can already do this, by using the 

```js
import { createYjsProvider } from "@y-sweet/client";

const provider = createYjsProvider(yDoc, clientToken);
```

not sure what specifically you are looking for tho.

**Comment by seleckis** [comment]
And how to pass HocuspocusProvider to the code you provided?

**Comment by websiddu** [comment]
You don't need both HocuspocusProvider and YSweetProvider, its either or. You can do all the things that you are doing with HocuspocusProvider with YSweetProvider, i thin the only difference is in how you get the doc, in Hocuspocus you will `myHocusPocusProvider.document` and with YSweet you will `myYSweetProvider.doc`

**Comment by paulgb** [comment]
We could make the client library (react hooks) work with a non Y-Sweet provider though -- I think that's what @seleckis is looking for?

I've been a bit hesitant to go down this path because some of the things the client library does (like adding a debug URL) only make sense in a Y-Sweet context, and I worry about adding complexity to the code to handle both cases.

**Comment by websiddu** [comment]
I'm not sure why you need that tho, Y.Doc also accepts multiple providers at the same time. You can just keep using the createYjsProvider function to create a provider. 

```jsx
  // my-app-provider.tsx

const MyAppProvideComponent = (props: MyAppProviderProps) => {
  const provider = useMemo(() => {
    return createYjsProvider(yDocFromStore, clientToken);
   }
   
   useEffect(() => {
      provider.on("sync", () => {
        setConnected(true);
      });
  
      return () => {
        provider.off("sync", setConnected);
      };
  }, [provider]);

  return (
    <MyAppContext.Provider value={{ provider }}>
      {children}
    </MyAppContext.Provider>
  );
};  
```

```jsx
  // page.tsx (server page)
  
  const clientToken = await getOrCreateDocAndToken(
    "http://127.0.0.1:8083/", // your y-sweet URL
    params.id
  );
  
  <YDocProvider clientToken={clientToken}>
      {children}
  </YDocProvider>
```

**Comment by seleckis** [comment]
@paulgb exactly

@websiddu  I have already created my set of hooks to work with yjs shared types, so I don't need y-sweet anymore. Thank you for your time.
