### ISSUE TITLE
Feature Request: Support for MySQL and MongoDB Integration

### ISSUE THREAD

**Issue by dwzkit** [drifting-in-space/y-sweet#189]
Hello y-sweet Team,

I hope this message finds you well. I am writing to propose a feature request for the integration of MySQL and MongoDB storage solutions. This feature would greatly enhance the capabilities of y-sweet , providing more flexibility and options for data storage and management.

Proposed Implementation:
While I am not entirely sure about the technical intricacies, a possible approach could be creating adaptable connectors or plugins that allow seamless communication between y-sweet and these databases.

Additional Considerations:
I understand that integrating new features requires careful consideration, especially in terms of maintenance and compatibility. I believe, however, that this addition could significantly increase the utility and appeal of y-sweet.

Thank you for considering this request. I look forward to any discussion on this proposal and am happy to contribute further if needed.

**Comment by paulgb** [comment]
Hi @dwzkit, thanks for the suggestion, but we are unlikely to add other storage backends beyond S3-compatible blob storage to y-sweet. For background on why I think blob storage is a better choice than databases for this task, see [this blog post](https://digest.browsertech.com/archive/browsertech-digest-figma-is-a-file-editor/).

Regards,

-- Paul

**Comment by websiddu** [comment]
Hi Paul, thanks for the great library. Are you thinking about version history at all? If we are using file bases storage, we still have a store a lot of small updates, that requires some sort of time stamping etc.. what do you recommend for such use cases?

**Comment by paulgb** [comment]
Hi @websiddu, yes, it's something I've thought about adding. The architecture is actually designed with version history in mind, but I haven't implemented it yet because I haven't had a concrete use case to think through. Can you tell me a bit about the use case you have in mind?

**Comment by websiddu** [comment]
Its a pretty common use cases for a collaborative apps, if someone changes something without others approvals, you always want to go back to a previous version. Similar to Figma or Google Docs. Efficiently storing the version history is the hardest problem and none have really solved it, (at least in the open source community). 

It will be wonderful if y-sween can be extended for such use cases.

**Comment by websiddu** [comment]
Are there any plans to support that in the future?

**Comment by paulgb** [comment]
There is! I don't have a concrete timeline now though because we are focused on a big https://plane.dev rewrite. (The plan is for Y-Sweet to support Plane as a way to scale up the native client).
