### ISSUE TITLE
Linux arm64 support

### ISSUE THREAD

**Issue by gempir** [drifting-in-space/y-sweet#206]
Would love support for arm64 on linux, since it's becoming more common on several cloud providers.

```
Unsupported platform: Linux arm64
```

**Comment by paulgb** [comment]
Good idea, should be doable.

**Comment by paulgb** [comment]
As of 0.1.1, arm64 works! Thanks for the suggestion @gempir 

<img width="1150" alt="image" src="https://github.com/drifting-in-space/y-sweet/assets/46173/77d621d6-e41b-470c-9c0f-2760f43a38bf">

**Comment by gempir** [comment]
That was really fast. Thank You ❤️
