### ISSUE TITLE
Tree CRDT demo double-click causes accidental select

### ISSUE THREAD

**Issue by paulgb** [drifting-in-space/y-sweet#78]
Demo:

https://github.com/drifting-in-space/y-sweet/assets/46173/9cd17ab0-0399-4a1b-a563-c7e0e252cea0

I tried the usual things (`stopPropagation`, `preventDefaults`) to no avail.

**Comment by rishi-raj-jain** [comment]
Hey @paulgb 

- Where would you need this fix to be landed (react, other packages?)
- Can you describe the issue in more detail and what's expected?

**Comment by paulgb** [comment]
Hi @rishi-raj-jain, the fix will likely be confined to this file: https://github.com/drifting-in-space/y-sweet/blob/main/examples/src/app/tree-crdt/TreeView.tsx

To run the examples locally, you need an API token, you can use this one:

```bash
# in examples/ directory
Y_SWEET_CONFIG=https://AAAg80YKO6JS5rRZQaeQe83q2OhTDIR15RuO2B6d4qOFqyI@y-sweet.net/project/j-d3PuT7jGuGcdYHzIw-u/ npm run dev
```

**Comment by rishi-raj-jain** [comment]
@paulgb Done!

**Comment by rishi-raj-jain** [comment]
As the nodes have nothing behind them, the usual select in kicking in. Adding select-none resolves that.

**Comment by rishi-raj-jain** [comment]
Does work fine, even if I click on the cornerest point haha

**Comment by rishi-raj-jain** [comment]
Hey @paulgb 

Can I get the bounty reward set on this given my solution is merged?

**Comment by kremedev** [comment]
https://github.com/drifting-in-space/y-sweet/pull/79 this still selects it? I made CopyLink component select none to completely fix it

**Comment by rishi-raj-jain** [comment]
Thank you @paulgb!

**Comment by paulgb** [comment]
There we go, I guess it just took a few minutes.

I see what you mean @kremedev, I only tested on double-clicking on tree nodes. In any case, it's been claimed, thanks all.
